service: aws-python-scheduled-cron

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  cron:
    handler: handler.run
    events:
      # Invoke Lambda function every 10 minute
      - schedule: rate(10 minute)
  secondCron:
    handler: main.run
    events:
      # Invoke Lambda function every 10th minute from Mon-SUN
      - schedule: cron(0/10 * ? * MON-SUN *)